name: project_oneplanet
description: oneplanet - onegoal

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.2.0
  circular_reveal_animation: ^2.0.1
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  cloud_firestore: ^4.4.5
  google_sign_in: ^6.0.2
  cached_network_image: ^3.2.3
  rive: ^0.10.1
  uuid: ^3.0.7
  google_maps_flutter: ^2.2.5
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/riveanimation/
    - assets/images/
